name: flutterwithfirebase
description: Flutter with Firebase
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  firebase_auth:
  google_sign_in: 3.0.0
  cloud_firestore:
  flutter_staggered_grid_view:
  firebase_admob:
  firebase_analytics:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/